apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: loghmeh-client
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2020-06-11T17:29:58Z"
  name: loghmeh-client
  selfLink: /api/v1/namespaces/baharan-aylin-ns/services/loghmeh-client
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: loghmeh-client
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
